# site name
prefixName: 
siteName: 唐川的博客
# favicon and site master avatar
favicon: https://cdn.jsdelivr.net/gh/JLUtangchuan/JLUtangchuan.github.io@master/images/favicon.png
avatar: https://cdn.jsdelivr.net/gh/JLUtangchuan/JLUtangchuan.github.io@master/images/cat.jpg
url: http://blog.tangchuan.ink
description: 唐川的博客
cdn: # https://cdn.jsdelivr.net/gh/JLUtangchuan/picBed@dev
pjax: 1
# 1开启
mathjax: 1

notice: 
lazyloadImg: https://cdn.jsdelivr.net/gh/JLUtangchuan/picBed@dev/img/20200704223047.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-gears }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    论文: {path: /categories/论文/, fa:  fa-graduation-cap }, 
    编程: {path: /categories/编程/, fa: fa-code },
    数学: {path: /categories/数学/, fa: fa-diamond }
  } }
  人文: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    笔记: {path: /categories/读书笔记/, fa: fa-th-list faa-bounce }, 
    书单: {path: /books/, fa: fa-book faa-vertical }, 
    影视: {path: /movies/, fa: fa-film faa-vertical }, 
    # 歌单: {path: /music/, fa: fa-headphones },
    随记: {path: /categories/随记/, fa: fa-calendar-check-o  },
    诗词: {path: /categories/诗词/, fa: fa-file-powerpoint-o }
  } }
  # 编程: {
  #   {path: /categories/Python/, fa: fa-code },
  #   {path: /categories/Tensorflow/, fa: fa-code },
  #   {path: /categories/Tensorflow/, fa: fa-code },
  # }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  #友人帐: { path: /links/, fa: fa-link faa-shake }
  #赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  #关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
  #  我？: {path: /about/, fa: fa-meetup}, 
  #  主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
  #  Lab: {path: /lab/, fa: fa-cogs },
  #} }
  # 客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://cdn.jsdelivr.net/gh/JLUtangchuan/picBed@dev/img/20200704223421.jpg
  - https://cdn.jsdelivr.net/gh/JLUtangchuan/picBed@dev/img/夜景.jpg
  - https://cdn.jsdelivr.net/gh/JLUtangchuan/picBed@dev/img/城市夜景.jpg

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dim

# startdash url, title, desc img
# startdash: 
  # - {url: /theme-sakura/, title: Sakura, desc: 本站 hexo 主题, img: /img/startdash/sakura.md.png}
  # - {url: http://space.bilibili.com/271849279, title: Bilibili, desc: 博主的b站视频, img: /img/startdash/bilibili.jpg}
  # - {url: /, title: hojun的万事屋, desc: 技术服务, img: /img/startdash/wangshiwu.jpg}



# your site build time or founded date
siteBuildingTime: 01/01/2020

#social  url, img PC端配置
social:
  github: {url: https://github.com/JLUtangchuan/, img: https://cdn.jsdelivr.net/gh/JLUtangchuan/picBed@dev/img/20200704233356.png}
  # sina: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/sina.png}
  wangyiyun: {url: https://music.163.com/#/user/home?id=382522283, img: https://cdn.jsdelivr.net/gh/JLUtangchuan/picBed@dev/img/20200704233212.png}
  zhihu: {url: https://www.zhihu.com/people/tang-chuan-5-26, img: https://cdn.jsdelivr.net/gh/JLUtangchuan/picBed@dev/img/20200704233139.png}
  # email: {url: http://weibo.com/mashirozx?is_all=1, img: /img/social/email.svg}
  # wechat: {url: /#, qrcode: /img/custom/wechat.jpg, img: /img/social/wechat.png}

#social  url, img 移动端配置
msocial:
  github: {url: http://github.com/JLUtangchuan, fa: fa-github, color: 333}
  # weibo: {url: http://weibo.com/mashirozx?is_all=1, fa: fa-weibo, color: dd4b39}
  # qq: {url: https://wpa.qq.com/msgrd?v=3&uin=954655431&site=qq&menu=yes, fa: fa-qq, color: 25c6fe}

donate:
  paypal: # https://www.paypal.me/hojuncn
  alipay: # /img/custom/donate/AliPayQR.jpg
  wechat: # /img/custom/donate/WeChanQR.jpg
  wechatSQ: # /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: # https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: # Unbroken.mp4

aplayer: 
  id: 542358069
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: EYCWNriLnt4UiHM6LSnPFDcy-gzGzoHsz
v_appKey: cJnnePWrUXTh8l9vUJ1qdsF6

